email: support@earthly.dev
url: "https://earthly.dev"
docsurl: "https://docs.earthly.dev"
landingurl: "https://earthly.dev"
blogurl: "/blog/"
githuburl: "https://github.com/earthly/earthly"
twitter_username: earthlytech
github_username:  earthly
google_analytics: "UA-161831101-5"
slack_url: "/slack"
description: "Better Builds"
include:
  - _redirects
sass:
    load_paths:
        - _sass
        - node_modules
include: 
  - _redirects
  - robots.txt
plugins:
  - jekyll-feed
  - jekyll-inline-svg
