email: support@earthly.dev
url: "https://earthly.dev"
docsurl: "https://docs.earthly.dev"
landingurl: "https://earthly.dev"
blogurl: "/blog/"
githuburl: "https://github.com/earthly/earthly"
twitter_username: earthlytech
github_username:  earthly
slack_url: "/slack"
tagline: "Make Builds Super Simple"
description: "Fast, consistent builds with an instantly familiar syntax – like Dockerfile and Makefile had a baby. 
              Write builds once, and run them anywhere – on your laptop, remote, and in any CI. Great for monorepos 
              and polyrepos. Open source, 9000+ stars."
include:
  - _redirects
sass:
    load_paths:
        - _sass
        - node_modules
include: 
  - _redirects
  - robots.txt
plugins:
  - jekyll-feed
  - jekyll-inline-svg
collections:
  news:
    output: true