email: support@earthly.dev
url: "https://earthly.dev"
docsurl: "https://docs.earthly.dev"
landingurl: "https://earthly.dev"
blogurl: "https://blog.earthly.dev"
twitter_username: earthlytech
github_username:  earthly
google_analytics: "UA-161831101-3"
google_analytics_rollup: "UA-161831101-5"
slack_url: "/slack"
description: "Better Builds"
include:
  - _redirects
sass:
    load_paths:
        - _sass
        - node_modules

# force include node_modules
exclude: []
# Build settings
plugins:
  - jekyll-feed
  - jekyll-inline-svg


collections:
  blog:
    output: true
    permalink: /blog/:slug/


