name: Publish Alerts

on:
  # run everyday at 12:15 utf ( 8:15 am est) to alert on new posts
  schedule:
    - cron: '15 12 * * *' 
  push:

jobs:
  build-website:
    name: Build Alert List
    runs-on: ubuntu-latest
    steps:
      - uses: FranzDiebold/github-env-vars-action@v2
      - name: Checkout code
        uses: actions/checkout@v2
      ## Write into published.txt what's been published
      ## Write into steps.published_check.outputs the outputs
      ## Problem - this doesn't seem to get more than one result
      ##           Might need to use published.txt rather than output
      - name: Has new published documents
        id: published_check
        run: |-  
          #  if [ "$CI_ACTION_REF_NAME" == "main" ]; then
            echo "3"
            pattern=$(date '+%Y-%m')
            if test -n "$(find ./blog/_posts -maxdepth 1 -name "*$pattern*" -print)"
            then
              echo "PUBLISHED=1" >> $GITHUB_ENV
              find ./blog/_posts -maxdepth 1 -name "*$pattern*" -print > posts.txt
              awk '{ print "https://earthly.dev/blog/"substr( $0, 26, length($0)-28 ) }' < posts.txt | tr '\n' "," | sed 's/,/, /g' 
              echo 'PUBLISHED_LIST<<EOF' >> $GITHUB_ENV
              awk '{ print "https://earthly.dev/blog/"substr( $0, 26, length($0)-28 ) }' < posts.txt >> $GITHUB_ENV
              echo '\n' >> $GITHUB_ENV
              echo 'EOF' >> $GITHUB_ENV
              cat $GITHUB_ENV
              echo "list: $PUBLISHED_LIST"
            fi
          #  fi

      ## Check output value for whether file exists
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "posts.txt"
      # Output published list
      - name: Slack Notification
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        if: steps.check_files.outputs.files_exists == 'true'
        with:
          # This is set in the webhook it seems
          channel-id: 'alerts'
          payload: |
            {
              "text": "Published blog posts: ${{ env.PUBLISHED_LIST }}"
            }
        env:
          SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK